import { useEffect } from 'react';
import Head from 'next/head';
import Header from '@/components/Header';
import Hero from '@/components/Hero';
import Posts from '@/components/Posts';

export default function Home() {

  return (
    <>
      <Head>
        <title>👋 khalid&apos;s blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='max-w-6xl mx-auto px-6'>
        <Header />
        <div className='max-w-6xl mx-auto'>
          <Hero />
          <Posts />
        </div>
      </div>
    </>
  )
}